### ISSUE TITLE
Change collection_vars to collection

### ISSUE THREAD

**Issue by tataraba** [render-engine/render-engine#259]
Accessing attributes from `Collection` class can be done using `collection_vars`. Seems a little more intuitive to reference as just `collection`.

from:
`_page.collection_vars = self.to_dict()`

to:
`_page.collection = self.to_dict()`

**Comment by kjaymiller** [comment]
@all-contributors please add @tataraba for code

**Comment by kjaymiller** [comment]
https://github.com/all-contributors please add @tataraba for code

**Comment by kjaymiller** [comment]
@all-contributors please add @tataraba for cli

**Comment by kjaymiller** [comment]
@all-contributors please add @tataraba for code
