### ISSUE TITLE
--reload feature needs docs

### ISSUE THREAD

**Issue by LauraLangdon** [render-engine/render-engine#321]
The new `--reload` feature hasn't yet been documented.

**Comment by kjaymiller** [comment]
going to cc: @tataraba on this. I think it would be good to chat about the best way to document this.

My suggestions are:
- Be sure to add an admonition about this being in beta
- Usage
- What will trigger a reload
- What WON'T trigger a reload (`__*` files, and changes that importlib won't be able to pick up.)

**Comment by kjaymiller** [comment]
@all-contributors please add @LauraLangdon  for Documentation
