### ISSUE TITLE
replace black with ruff

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#334]
I don't personally care too much about the Black vs Ruff debate in terms of usage.

Ruff does what black does at this point and more and we're using both so unless there is a concern, we can remove black as a dependency.

## To Complete

- [x] Remove references to black in documentation
- [X] Remove using black in any github actions

**Comment by Mahhheshh** [comment]
so remove and update black references from these files?

-  .devcontainer/devcontainer.json

- .github/CONTRIBUTION.md
