### ISSUE TITLE
Switch to Annotated option of typer

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#360]
Typer recommends the annotated option for typer applications. 

It would be good to upgrade to the Annotated versions in our CLI applications.

https://github.com/render-engine/render-engine/blob/35d7c9590b0c29ff896f209e21eaeb969af258e2/src/render_engine/cli/cli.py#L147

- [ ] init
- [ ] build
- [x] serve

**Comment by Mahhheshh** [comment]
is this correct??
 ```python
 collection_path: Annotated[pathlib.Path, typing.Optional] = typer.Option(
        pathlib.Path("pages"),
        help="create your content folder in a custom location",
        rich_help_panel="Path Options",
    )
```

**Comment by kjaymiller** [comment]
It's an issue with order. Typer's recommendation is correct.

I'm happy to help with some of the annotations if you want to start with `init`.

Happy to help more if needed.

**Comment by Mahhheshh** [comment]
> I'm happy to help with some of the annotations if you want to start with `init`.

sure!!
