### ISSUE TITLE
Move Wiki from .github render-engine

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#365]
for two reasons.

1. I originally added it to `.github` as I thought that would make it available in the org main. Since it doesn't it doesn't make sense to be added to it there.

2. I keep looking for it there anyway and it would help if it were in the root.

**Comment by john0isaac** [comment]
@kjaymiller What do you mean by making it in the root? where do you want to move it? here in the https://github.com/render-engine/render-engine repo or somewhere else?

**Comment by kjaymiller** [comment]
I've been trying to figure out the best place for the greater ecosystem to live. 

My natural inclination is some render-engine site that people can contribute to, but that's another thing to manage. 

I had a wiki in the `.github` repo that I've been adding things to (Probably outdated now) and was saying it didn't make sense for it to be in the `.github` repo because folks are looking there. They're likely going to start in the render-engine repo so it would be better if the wiki was there. 

Of course this may be a non-issue as again I'm not confident that the wiki is the long-term solution.

**Comment by john0isaac** [comment]
@kjaymiller can you enable wikis from the setting of this repo so I can move it here?

**Comment by john0isaac** [comment]
fixed by #569
