### ISSUE TITLE
`ImportDevcontainer - Error: attempted relative import with no known parent package`.

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#383]
Sure, Will try to fix 360 along with this one. 
Btw I have done the setup for the project within vscode devcontainer, but I am unable to run the scripts. I am getting `ImportError: attempted relative import with no known parent package`.

_Originally posted by @Mahhheshh in https://github.com/render-engine/render-engine/issues/343#issuecomment-1821544638_

**Comment by Mahhheshh** [comment]
details:
![image](https://github.com/render-engine/render-engine/assets/100200105/c60e0e06-40b8-4ff7-86b0-06a734058a87)
Also, The contribution guidelines, specified in both Contributing.md and .github/Contribution.md, lack detailed instructions on setting up the project locally for potential contributors.

**Comment by kjaymiller** [comment]
Were you able to fix that relative import locally. (The issue should be to fully import using

`from .render_engine.cli.cli import app`

What's interesting is I've never called it using

`python3 src/render_engine`

instead I've used 

`render-engine <CLI COMMANDS>` or `python -m render-engine <CLI COMMANDS>`

**Comment by Mahhheshh** [comment]
thanks! running `python3 -m render_engine <CLI COMMANDS>` solves the issue.
