### ISSUE TITLE
better typing for return attributes

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#427]
https://github.com/render-engine/render-engine/blob/b9979a34f76f134ad3cdc758c8d220850cfa983c/src/render_engine/parsers/base_parsers.py#L22

create a return object that is called

**Comment by Mahhheshh** [comment]
I'm interested in addressing this issue. Can you please provide me with additional details?

**Comment by kjaymiller** [comment]
So that dict is something a little more defined as it's a `dict[str, any]`. There is also the attribute that was added in Python 3.10 where you can define a type and pass that type.

```python
parsed_content: str
parsed_attributes: dict[str, any]

def parse_content(..., ...) -> tuple[parsed_attributes, parsed_content]
```
Doing this means that we can provide more in-depth typing and documentation that can also then be attached to better validation in the future.

**Comment by kjaymiller** [comment]
I do think at this point we're still in the discussion phase of things but happy to get the process started.

**Comment by Mahhheshh** [comment]
Got it, Also I want to know if changes will be made in the entire codebase or just in a few files. I have exams, so it may take time for me to make these changes.

**Comment by kjaymiller** [comment]
For this issue I was just refering to that particular file.

**Comment by john0isaac** [comment]
there is a merged PR related to this issue is it safe to close it?

**Comment by kjaymiller** [comment]
Yes
