### ISSUE TITLE
Remove unused functions from `cli.py`

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#479]
https://github.com/render-engine/render-engine/blob/20660cc14f55d863fb0fd8f014193b7d6b8e2163/src/render_engine/cli/cli.py#L39

**Comment by kjaymiller** [comment]
#465 needs to be completed first before we can implement this

**Comment by Izaan17** [comment]
I would like to help out! Please give me more information.

**Comment by kjaymiller** [comment]
Jump into the Discord or check out some of the issues. We'd be happy to have your help!
