### ISSUE TITLE
[Bug]: render-engine init not rendering cli arguments correctly

### ISSUE THREAD

**Issue by john0isaac** [render-engine/render-engine#505]
### Summary Of Actions

When I initialize a template with title and description it doesn't convert the template to the correct python code.

It should be 
```JSON
{
"SITE_TITLE" : "Hello world",
"SITE_DESCRIPTION" : "simple site for testing"
}
```
Not
```JSON
{
SITE_TITLE : "Hello world",
SITE_DESCRIPTION : "simple site for testing"
}
```

![image](https://github.com/render-engine/render-engine/assets/64026625/df4ccbbc-bbe4-48d7-9fd3-f142f26a0a6a)

### Operating System

Windows

### What Python Version are you using?

Python 3.10

### Have you installed Plugins/Themes/Custom Parsers?

NO

### What did you enter to get the output that you recieved?

```shell
render-engine init --owner-name="John Aziz" --owner-email="example@gmail.com" --title="Hello world" --site-description="simple site for testing"
```

### Output

```shell
app.site_vars.update({
    SITE_TITLE:"Hello world",
    SITE_DESCRIPTION:"simple site for testing",
    "OWNER":{
        "name": "John Aziz",
        "email": "example@gmail.com",
    },
    "NAVIGATION":[
        {
            "name": "Home",
            "url": "/",
        },
        {
            "name": "Collection Page",
            "url": "/example-page.html",
        }
    ]
    })app.site_vars.update({
    SITE_TITLE:"Hello world",
    SITE_DESCRIPTION:"simple site for testing",
    "OWNER":{
        "name": "John Aziz",
        "email": "example@gmail.com",
    },
    "NAVIGATION":[
        {
            "name": "Home",
            "url": "/",
        },
        {
            "name": "Collection Page",
            "url": "/example-page.html",
        }
    ]
    })
```

**Comment by kjaymiller** [comment]
In the upcoming `2024.1.1` release we switch this init completely to cookiecutter which means these steps will not work as you believe.

**Comment by john0isaac** [comment]
@kjaymiller Note that the fix is only available using the github release the pypi release is still at [2023-10-4](https://pypi.org/project/render-engine/)

To get the update I used this command to install render engine if anyone faces the same issue:

```bash
pip install git+https://github.com/render-engine/render-engine.git#egg=render-engine
```
