### ISSUE TITLE
check for filename and use filename title before class.name

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#532]
Current Implementation uses the `__class__.__name__` attribute

https://github.com/render-engine/render-engine/blob/9df89d0f412106ce7be8770245cdff61ea6f2510/src/render_engine/_base_object.py#L19-L25

If there is a `content_path` defined, would it be better to use the filename instead.

This would solve a the issue of overwritting files in a collection when no title is provided.

I would also be okay with raising warnings for this case.

**Comment by JohananOppongAmoateng** [comment]
@kjaymiller  I think this issue needs to be closed
