### ISSUE TITLE
raise error with themes that have no prefix

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#533]
with render now pulling from the `prefix` that makes it mandatory and an error should be raised in no prefix is supplied.

This will likely be resolved by removing the `None` default.

**Comment by Tashuuuu** [comment]
I would like to work on it

**Comment by kjaymiller** [comment]
I would like to push the next stable that is being blocked by this. I will likely make this change myself on Friday (9 Feb) if not done.
