### ISSUE TITLE
Add Frontmatter to documentation files

### ISSUE THREAD

**Issue by john0isaac** [render-engine/render-engine#594]
- [x] #599
- [x] #600

Frontmatter may include

```md
---
title: "The document title"
description: "The document description"
date: February 18, 2024
tags: ["archive", "collection"]
---
```

**Comment by OsamaRab3** [comment]
I’m interested in contributing to it. Could you please let me know if it's still available and if there are any specific guidelines I should follow?

**Comment by john0isaac** [comment]
Hey @OsamaRab3 👋🏼,
Thank you for showing interest. It's is still available.
This issue is to keep track of #600 and #599.

Which one would like to work on? Or do you wanna work on both?


This is our [contributing guide](https://render-engine.readthedocs.io/en/latest/contributing/CODE_OF_CONDUCT/) if you want to learn more about the process.


Simply put all you need to do is to add the lines I have included to the beginning of every markdown file inside the specific folder mentioned in the issue.

**Comment by john0isaac** [comment]
@allcontributors please add @OsamaRab3 for docs
