### ISSUE TITLE
Remove this line

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#615]
This was partially fixed in #613 but the original path was left in.

This line needs to be removed.

https://github.com/render-engine/render-engine/blob/e04b96c02d29566e3774cfe0891ce0a25f315501/.github/workflows/test.yml#L10

**Comment by MohitKambli** [comment]
Hello @kjaymiller,
Hope you're doing well.
I would like to work on this issue.
I have raised a potential PR that would resolve this issue.
If at all there is anything needed from me or if there's anything that I missed out, then do let me know.
Sincere apologies if I made any mistakes.

Thanks and Regards,
Mohit Kambli

**Comment by kjaymiller** [comment]
@all-contributors please add @MohitKambli for infra
