### ISSUE TITLE
Enroll Render Engine in Holopin OpenSource program

### ISSUE THREAD

**Issue by john0isaac** [render-engine/render-engine#631]
Can you enroll render-engine in this?
https://www.holopin.io/opensource
It would be awesome to distribute Holopin digital badges for contributors just like hacktoberfest.

**Comment by kjaymiller** [comment]
@john0isaac - I just ran through the signup form and there seems to be a lot (including creating a design for the pin)

If you want to own this task, I won't stop you but I'm personally not completely convinced the work is worth it.

**Comment by john0isaac** [comment]
Sure I will try and see, it's a very encouraging thing for freshers that's why I suggested it.
