### ISSUE TITLE
Create Windows Test in Matrix

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#738]
There was a pickling error on windows in development for the file-watch and rebuild.

We need to run tests on Windows as well to make sure there are differences.

**Comment by OsamaRab3** [comment]
What are the steps to set up a testing environment on Windows to verify the pickling issue?

**Comment by kjaymiller** [comment]
If you take a look at  the matrix in the GitHub action it's currently only running on linux (but with multiple python versions).

You'll need to enable the windows runner - https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#using-a-matrix-strategy. 

I would suggest enabling actions on your fork.

You should be able to also trigger the workflow manually since `manual-dispatch` is configured.
