### ISSUE TITLE
Upload Artifact isn't creating unique names for each version

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#748]
![results from upload artifact showing a failure](https://github.com/user-attachments/assets/696a0958-2233-4326-9814-c9e35516d2d1)

**Comment by OsamaRab3** [comment]
I noticed that you raised this issue regarding the conflict error when running GitHub Actions for MacOS testing. I encountered the same error while trying to implement the  #747   if I updating the artifact name to make it unique for each workflow run by appending `${{ github.run_id }}`  Could you please confirm if this approach is appropriate, or suggest any alternative solutions to resolve

**Comment by kjaymiller** [comment]
That would solve the issue yes

**Comment by kjaymiller** [comment]
@OsamaRab3 I was mistaken apparently the run is based on the GH Action call which means that with there being a couple runs I would suggest that you also include the operating system and python version:

- ${matrix.python_version}
- ${RUNNER_OS}

There won't be a python version matrix for the run on latest so don't include it there.

**Comment by kjaymiller** [comment]
Closing as plans are to remove coverage artifact uploads
