### ISSUE TITLE
Fixing the install instructions on the CLI

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#758]
The readme and the docs are a mess.

I have some potential solutions:

- rename extras to `[all]` to include the CLI components ([this is similar to fastapi](https://github.com/fastapi/fastapi/blob/22bf988dfb085f45449bc137401af0105a86cdf5/pyproject.toml#L77-L101))
- rename `[extras]` to `[cli]` and remove the sitemap installation and move `watchfiles` over to it.

#### Why

From the [docs in cli](https://render-engine.readthedocs.io/en/latest/cli/)

> creating your app with render-engine init
> The init command is a hook to call [cookiecutter](https://github.com/cookiecutter/cookiecutter).
> 
> This allows you to quickly create or augment your render-engine site using a pre-existing cookiecutter template.

Half of the cli components are install but only cookiecutter isn't. If we're splitting the CLI install from the rest of the render engine dependencies then all of the cli only components should be installed separately.

It should include the install portion for the cli components which

Another option is to install the

**Comment by kjaymiller** [comment]
cc: @john0isaac what are your thoughts?

**Comment by john0isaac** [comment]
I agree, this would simplify the installation and make the package smaller.
We will need `[all]` for everything and `[cli]` for cli are we missing anything else that needs to be restructured?

**Comment by kjaymiller** [comment]
I think we could have a set of Plugins that we include for `extras` but honestly I don't know what those plugins are.
