### ISSUE TITLE
Clarify static_path management

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#797]
in this section - https://render-engine.readthedocs.io/en/latest/theme_management/#handling-static-files.

Change:

> Unlike templates you can have more than one static_path you wish to include. You can add mores static paths using site.static_path.add("<path/to/static>").

to

> Static Paths are managed by the Site's theme_manager and you can many static_paths. You can add more static paths using site.static_paths.add("<path/to/static>").

**Comment by OsamaRab3** [comment]
@kjaymiller I will start working on the requested changes, or is this change not needed?

**Comment by kjaymiller** [comment]
feel free to add this one
